name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem or use case
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the Solution
      description: A clear and concise description of what you want to happen
      placeholder: "The feature should allow users to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "Another approach could be..."

  - type: checkboxes
    id: components
    attributes:
      label: Affected Components
      options:
        - label: Frontend
        - label: Backend
        - label: Database
        - label: Authentication
        - label: Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add screenshots, mockups, or any other helpful information

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
